### ISSUE TITLE
重新恢復sql 資料時遇到問題

### ISSUE THREAD

**Issue by tiruhsu** [QingdaoU/OnlineJudgeDeploy#114]
![螢幕快照 2024-06-28 18-28-51](https://github.com/QingdaoU/OnlineJudgeDeploy/assets/102364663/d4c130a0-046e-44f8-9d60-d72b20d52f7f)
執行完docker cp db_backup_xxxxxxx.sql onlinejudgedeploy_oj-postgres_1:/root
docker exec -it onlinejudgedeploy_oj-postgres_1 bash
之後,遇到psql: FATAL:  role "postgres" does not exis 的問題
我不知道是不是我不熟悉bash或是container拉錯了
因為原本的onlinejudgedeploy_oj-postgres_1 是寫oj-postgres

**Comment by mikucat0309** [comment]
PostgreSQL 的 user 一直都是 `onlinejudge`，所以會是 `psql -U onlinejudge`

**Comment by tiruhsu** [comment]
感謝，原來是這樣，我會再試試看的，謝謝你
