### ISSUE TITLE
SELinux环境下无法成功部署

### ISSUE THREAD

**Issue by rewqazxv** [QingdaoU/OnlineJudgeDeploy#12]
fedora 27 server, 自带selinux, 容器 judge-server  oj-postgres oj-redis 无限重启, 显示各种Permission denied . 目前需要关闭selinux才能正常使用

**Comment by rewqazxv** [comment]
judge-server 的输出
```
mkdir: cannot create directory '/judger/run': Permission denied
mkdir: cannot create directory '/judger/spj': Permission denied
chown: cannot access '/judger/spj': No such file or directory
Error: Error: '/log/gunicorn.log' isn't writable [PermissionError(13, 'Permission denied')]
```

oj-postgres 的输出
```
chown: /var/lib/postgresql/data: Permission denied
```

oj-redis 的输出
```
chown: .: Permission denied
```

**Comment by virusdefender** [comment]
感谢，是存在这样的问题，https://docs.onlinejudge.me/#/onlinejudge/faq?id=centos-%E4%B8%8A%E9%83%A8%E7%BD%B2%E9%81%87%E5%88%B0%E9%97%AE%E9%A2%98 也有提到

建议先关闭
