### ISSUE TITLE
ntfs

### ISSUE THREAD

**Issue by Zoctan** [QingdaoU/OnlineJudgeDeploy#13]
if docker-compose.yml is in ntfs file system, postgres will not run successfully:
initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted

**Comment by virusdefender** [comment]
you can try to run you cmd or powershell with administrator user

**Comment by Zoctan** [comment]
oh, there are two disk in my computer, one is ext4 and the other is ntfs, only linux system was installed.
when the oj project was placed in ntfs, the problem will exist.
solved: move project to ext4 or other which linux system can use `chown -R postgres /var/lib/postgresql/data` to change user owner.

**Comment by zema1** [comment]
It's buggy to install the oj  in Windows. You would better create a virtual machine using Hyper-V or VMware etc. And install the oj in it.
