### ISSUE TITLE
如何导入题目啊

### ISSUE THREAD

**Issue by Dreamcreationman** [QingdaoU/OnlineJudgeDeploy#17]
作为小白，实在是不知道如何导入题目，求教，比如在群里给出的蓝桥杯的压缩包，要如何导入呢

**Comment by zema1** [comment]
群里的那个可以用这个方式导入 https://docs.onlinejudge.me/#/onlinejudge/from_old 之前是没有题目导出导入的，所以用了这个比较扭曲的方式
