### ISSUE TITLE
无法添加中文题目？

### ISSUE THREAD

**Issue by 15281029** [QingdaoU/OnlineJudgeDeploy#2]
是我的原因还是本身就是这样设计的？
发布带有中文的题目的时候，任何有中文的文本框出现的时候就会出现这样的提示：
input_description : This field may not be blank.

**Comment by virusdefender** [comment]
不是啊，可能是js有问题？

**Comment by 15281029** [comment]
JS没有问题吧，chrome里没有显示任何错误

**Comment by 15281029** [comment]
@virusdefender 在题目设置下发现了一个不知道是不是的BUG：
在网页端的文本编辑框中直接输入中文，提交后会提示【input_description : This field may not be blank.】
可是如果中文是复制到文本框中的时候就没有任何问题，这个不是到时我的问题还是bug,如果是我的问题，我没有检查出是哪里出了问题，还请大大做进一步确认。

**Comment by virusdefender** [comment]
但是我这无法复现呢，你方便加一下 readme 中的qq群么，然后私聊群主，我单独帮你看下。

**Comment by oneofsunshine** [comment]
我也遇到这种问题了。粘帖上可以，输入会弹框`title : This field may not be blank.`

**Comment by takfate** [comment]
这个问题不是貌似可以强行解决么。。不管什么时候，弄完中文，在最后打个空格QAQ

**Comment by virusdefender** [comment]
麻烦各位 

```
docker pull registry.cn-hangzhou.aliyuncs.com/qduoj/oj_web_server 
```

然后
 
```
docker-compose up -d 
```

应该就没问题了，是特定版本的前端框架的bug
