### ISSUE TITLE
there is a 404 error on aliyun 

### ISSUE THREAD

**Issue by foxes1998** [QingdaoU/OnlineJudgeDeploy#25]
root@debian:~/OnlineJudgeDeploy#docker-compose up -d
Pulling judge-server (registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server:latest)...
ERROR: Get https://registry.cn-hangzhou.aliyuncs.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

似乎在阿里云上的镜像不见了，请问是否可以更新一下镜像？

**Comment by virusdefender** [comment]
是连接超时了，看了下镜像还在，可以重试下或者使用 https://cloud.docker.com/u/qduoj/repository/list
