### ISSUE TITLE
关于准备安装文件的问题

### ISSUE THREAD

**Issue by fanliyong007** [QingdaoU/OnlineJudgeDeploy#5]
“然后编辑 docker-compose.yml 将43行的TOKEN和第58行的JUDGE_SERVER_TOKEN修改为自定义的值， 两处值必须相同且 = 前后不能有空格”，对doker不是很了解，求问43行的TOKEN和58行的JUDGE_SERVER_TOKEN的值代表什么意思

**Comment by virusdefender** [comment]
那就别改了
