### ISSUE TITLE
提示“无法访问此网站”

### ISSUE THREAD

**Issue by dong628** [QingdaoU/OnlineJudgeDeploy#50]
![Screenshot_20200714_103308](https://user-images.githubusercontent.com/38680774/87374899-91925a80-c5bd-11ea-9107-cc95182b62cb.jpg)
我用的是树莓派，运行`docker-compose up -d`未报错，但是浏览器访问时，提示“无法访问此网站”，
![Screenshot_20200714_103620](https://user-images.githubusercontent.com/38680774/87375739-f5b51e80-c5bd-11ea-9078-2f37f0046e1e.jpg)
![Screenshot_20200714_102613](https://user-images.githubusercontent.com/38680774/87375810-fea5f000-c5bd-11ea-9726-e59ecc4b9f98.jpg)

**Comment by renbaoshuo** [comment]
貌似镜像不支持arm...

**Comment by dong628** [comment]
> 貌似镜像不支持arm...
> 
> 你这都写着 `restarting` 了。

啊这。。Docker和安装过程貌似都很正常。。
restarting代表什么，会生成日志么？我并不懂这个。。

**Comment by renbaoshuo** [comment]
> > 貌似镜像不支持arm...
> > 你这都写着 `restarting` 了。
> 
> 啊这。。Docker和安装过程貌似都很正常。。
> restarting代表什么，会生成日志么？我并不懂这个。。

Docker 也是有 arm 平台支持的，所以安装正常

然后 `restarting` 就是有问题，原因很多，但是这个镜像我记得是不支持 arm 平台的，所以不行

**Comment by sorbose** [comment]
请问题主是否解决了这一问题，我也是使用树莓派，相同的情况
