### ISSUE TITLE
judge-server is unhealthy

### ISSUE THREAD

**Issue by Muzihuzi** [QingdaoU/OnlineJudgeDeploy#56]
I can't find reason why my judge server is unhealthy
If I try to connect to the localhost It gives me an error message.
![1](https://user-images.githubusercontent.com/55011525/93660556-28cad100-fa8b-11ea-9a0e-9d5af6549308.PNG)
![fds](https://user-images.githubusercontent.com/55011525/93661277-85c98580-fa91-11ea-9bc0-e58e12c2384d.PNG)

**Comment by Muzihuzi** [comment]
and postgres server restarts every few seconds.

**Comment by virusdefender** [comment]
`docker logs oj-postgres` 看下日志

**Comment by Muzihuzi** [comment]
> `docker logs oj-postgres` 看下日志

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
2020-09-19 06:47:01.539 UTC [29] LOG:  could not link file "pg_wal/xlogtemp.29" to "pg_wal/000000010000000000000001": I/O error
2020-09-19 06:47:01.571 UTC [29] FATAL:  could not open file "pg_wal/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
2020-09-19 06:48:09.193 UTC [29] LOG:  could not link file "pg_wal/xlogtemp.29" to "pg_wal/000000010000000000000001": I/O error
2020-09-19 06:48:09.229 UTC [29] FATAL:  could not open file "pg_wal/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ... The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
2020-09-19 06:49:18.126 UTC [29] LOG:  could not link file "pg_wal/xlogtemp.29" to "pg_wal/000000010000000000000001": I/O error
2020-09-19 06:49:18.159 UTC [29] FATAL:  could not open file "pg_wal/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
running bootstrap script ...

**Comment by virusdefender** [comment]
你之前做了什么操作啊，看上去数据库文件不太对

**Comment by Muzihuzi** [comment]
什么也没做。 所以根本就猜不出个所以然来

**Comment by Muzihuzi** [comment]
> 你之前做了什么操作啊，看上去数据库文件不太对

什么也没做。 所以根本就猜不出个所以然来
