### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by che610369** [QingdaoU/OnlineJudgeDeploy#61]
當我對終端機輸入git clone -b 2.0 https://github.com/QingdaoU/OnlineJudgeDeploy.git && cd OnlineJudgeDeploy
這時就會顯示fatal: unable to access 'https://github.com/QingdaoU/OnlineJudgeDeploy.git/': Failed to connect to github.com port 443: Connection refused
求解決方案 謝謝

**Comment by virusdefender** [comment]
网络问题，GitHub 连不通，和 oj 本身无关
