### ISSUE TITLE
https域名证书

### ISSUE THREAD

**Issue by victorylin** [QingdaoU/OnlineJudgeDeploy#65]
部署qduoj的时候，用https域名来访问时，用户无法登录。

证书是这样一个二级域名的Nginx证书（有pem,key两个文件）
oj.xxx.com。

看到这段文字，如何理解和操作呢？有空帮回答一下哈，多谢了。

申请 HTTPS 证书

/.well-known 的 url 前缀，会自动使用 data/backend/ssl/.well-known 目录下面的文件，默认情况下 data/backend/ssl/ 已经存在，所以可以手动的创建 .well-known 及其子文件夹，比如需要 url 为 /.well-known/pki-validation/fileauth.txt 的验证文件，就可以创建 data/backend/ssl/.well-known/pki-validation/fileauth.txt 文件，内容为指定的内容。

然后替换 data/backend/ssl/ 下面的证书和私钥文件，之后 docker exec -it oj-backend sh -c "cd /app/deploy; supervisorctl restart nginx"

**Comment by victorylin** [comment]
这里的nginx是部署在宿主上的，通过SSL方式转发到宿主的端口，宿主的端口映射docker容器上的服务端口。这个时候docker容器还需要加载ssl证书？

**Comment by virusdefender** [comment]
nginx 是容器内的啊，如果你前面有 nginx，那 ssl 在那一层用就行了，然后 http 反向代理给容器的 nginx。

**Comment by victorylin** [comment]
前端部署了nginx，普通的访问ok的问题是无法登录啊。

**Comment by virusdefender** [comment]
配置的有问题吧，看看开发者工具里面的登录请求出了啥问题。容器内部有 nginx 的。

**Comment by victorylin** [comment]
访问题目列表都ok，login的报403错误，应该是访问限制。容器内的nginx 的https域名证书如何配置不是太清楚。

172.19.0.1 - - [26/Jan/2021:04:36:07 +0000] "POST /api/tfa_required HTTP/1.1" 403 571 "https://oj.xxx.cn/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" "61.152.132.170" 
172.19.0.1 - - [26/Jan/2021:04:36:07 +0000] "POST /api/login HTTP/1.1" 403 571 "https://oj.xxx.cn/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" "61.152.132.170" 
172.19.0.5 - - [26/Jan/2021:04:36:10 +0000] "POST /api/judge_server_heartbeat/ HTTP/1.1" 200 39 "-" "python-requests/2.24.0" "-"

**Comment by victorylin** [comment]
如何把阿里云申请的证书（pem，key文件），放到data/backend/ssl里来，具体的位置和文件名称如何定义？
文件夹的名称和域名关系么？

下面的这个描述不太好理解。

申请 HTTPS 证书

/.well-known 的 url 前缀，会自动使用 data/backend/ssl/.well-known 目录下面的文件，默认情况下 data/backend/ssl/ 已经存在，所以可以手动的创建 .well-known 及其子文件夹，比如需要 url 为 /.well-known/pki-validation/fileauth.txt 的验证文件，就可以创建 data/backend/ssl/.well-known/pki-validation/fileauth.txt 文件，内容为指定的内容。

**Comment by virusdefender** [comment]
去容器里面看下 nginx 配置文件你就懂了，就是去固定的位置加载固定文件名的证书文件。

**Comment by victorylin** [comment]
按说用宿主nginx采用ssl方式转发到容器的8000端口，容器内的nginx是不需要配置证书的，配置了也不影响。因为映射过来的就是非ssl的端口。反过来，从80端口直接转发到容器的ssl端口，会报错：The plain HTTP request was sent to HTTPS port。采用https方式就是登录不了。

**Comment by victorylin** [comment]
貌似是宿主nginx的配置问题，改了一个参数可以登录了。非常感谢你反馈和帮助，多谢了。
