### ISSUE TITLE
請問如何外部連線

### ISSUE THREAD

**Issue by jimmyhealer** [QingdaoU/OnlineJudgeDeploy#66]
我是用 WSL2 docker 架設，我不知道要如何外部連線，我對於 nginx 不是很了解。謝謝

**Comment by renbaoshuo** [comment]
您的 Docker 配置是什么样的？  
如果是默认安装的话应该可以直接使用 `https://wslip` 访问。

**Comment by jimmyhealer** [comment]
我完全沒有修改，直接架設，再確認一下 wslip 是要如何查詢?謝謝

**Comment by renbaoshuo** [comment]
WSL 的 IP 一般情况下可以使用 `ifconfig` 命令查询

![](https://user-images.githubusercontent.com/47095648/107876007-4bf49200-6efe-11eb-8edc-588f5ce22453.png)

如图中标橙色的部分即为 wsl 的 ip 。

---

如果需要外网访问，您需要将这个服务映射到外部。

**Comment by jimmyhealer** [comment]
那不好意思，請問如何把 服务映射到外部 ?

**Comment by renbaoshuo** [comment]
我个人不推荐映射 WSL 上的服务，因为 WSL 的 IP 会经常变动，建议您使用虚拟机（如 VMware 或 Virtual Box） 来搭建 OnlineJudge 服务，并在其中开启内网穿透服务。

我熟知的内网穿透服务提供商有这两个（仅供参考）：[Sakura Frp](https://natfrp.com) 和 [花生壳](https://hsk.oray.com) 。

**Comment by jimmyhealer** [comment]
好的感謝
