### ISSUE TITLE
使用ajax访问judge-server出现跨域的问题

### ISSUE THREAD

**Issue by kizzy8848** [QingdaoU/OnlineJudgeDeploy#67]

**Comment by kizzy8848** [comment]
建议在django的配置文件的设置可跨域的范围
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

**Comment by virusdefender** [comment]
judge_server 不应该与前端直接交互，否则会有安全问题，如果强行想搞，可以自己加一个 Nginx 做代理。
