### ISSUE TITLE
代码提交后，一直出现“等待评分”，该如何处理？

### ISSUE THREAD

**Issue by nangongfeng1** [QingdaoU/OnlineJudgeDeploy#71]
之前一直使用很正常，最近出现代码提交后无法判分，显示“等待评分”，后面提交的代码，都一直是“等待评分”，该如何解决！

**Comment by virusdefender** [comment]
看下后端日志，有问题再回复

**Comment by nangongfeng1** [comment]
实在不好意思，我不是专业出身，麻烦告知一下，如何查看后端日志，不胜感激！！！

**Comment by nangongfeng1** [comment]
2021-04-17 05:02:05,622 ERROR 
Traceback (most recent call last):
  File "/code/server.py", line 192, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 99, in judge
    output_dir=submission_dir)
  File "/code/compiler.py", line 44, in compile
    raise CompileError(error)
exception.CompileError

问题从17号开始出现的，不知道这个是不是关键地方！这个问题怎么解决呢？我后面查看过数据库，提交代码后，都好像没写入到数据库里。

**Comment by nangongfeng1** [comment]
你好，不知道如何称呼你，我一所中学的老师，没有学习过linux系统，能照到教程部署好青岛OJ ,实在是不容易。从去年年底部署好一直使用都非常正常，非常感谢开源OJ能提供给大家使用。


从4月17日开始，学生提交代码，一直显示“等待评分”，OJ几乎瘫痪，所以非常渴望能得到解决。
附件里是judge-server的日志

恳请帮助！！！感谢感谢！

**Comment by virusdefender** [comment]
`OnlineJudgeDeploy/data/backend/log` 下面的日志打包发一下

**Comment by nangongfeng1** [comment]
打包文件发不出，被退信了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QingdaoU/OnlineJudgeDeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QingdaoU/OnlineJudgeDeploy] 代码提交后，一直出现“等待评分”，该如何处理？ (#71)





 
OnlineJudgeDeploy/data/backend/log 下面的日志打包发一下

**Comment by nangongfeng1** [comment]
麻烦你告知一下邮箱或者QQ号，我单独给你发邮件或者加好友。感谢

**Comment by virusdefender** [comment]
https://docs.onlinejudge.me/#/onlinejudge/guide/qq_group
