### ISSUE TITLE
求在腾讯云服务器上怎么安装

### ISSUE THREAD

**Issue by OIer01** [QingdaoU/OnlineJudgeDeploy#77]
我在腾讯云服务器上登录我的服务器以后，安装报错，麻烦哪位大神已经在云服务器上安装过的，过来介绍一下经验。
<img width="364" alt="屏幕截图 2021-07-27 194210" src="https://user-images.githubusercontent.com/87971412/127147987-7fade4da-6d62-4797-b808-79fa3416ae1f.png">

**Comment by renbaoshuo** [comment]
这不是报错，只是 Warning ，我认为可以忽略。
