### ISSUE TITLE
提示未找到命令

### ISSUE THREAD

**Issue by OIer01** [QingdaoU/OnlineJudgeDeploy#79]
运行“git clone -b 2.0 https://github.com/QingdaoU/OnlineJudgeDeploy.git && cd OnlineJudgeDeploy”的时候，提示”sudo: docker-compose: command not found“，请问怎么解决？

**Comment by YuFengZe** [comment]
请仔细阅读文档：https://github.com/QingdaoU/OnlineJudgeDeploy
依赖中，首先要执行：
`sudo apt-get update && sudo apt-get install -y vim python3-pip curl git
pip3 install --upgrade pip
pip install docker-compose
`
然后安装docker：
`国内用户使用脚本一键安装: sudo curl -sSL https://get.daocloud.io/docker | sh
国外用户使用脚本一键安装: sudo curl -sSL get.docker.com | sh`
