### ISSUE TITLE
服务不可用后未自动重启

### ISSUE THREAD

**Issue by wwwumr** [QingdaoU/OnlineJudgeDeploy#87]
似乎没有配置健康指针检测服务可用情况，oj 平台部署后会不定时服务挂断（前端访问状态码为 500），不能自动重启
建议加上健康检测和自动重启功能。

健康检测方案：https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck
自动重启方案：https://hub.docker.com/r/willfarrell/autoheal/

**Comment by virusdefender** [comment]
核心原因还是得看下 500 时候的报错，比如数据库挂了重启 server 也没啥用。
